### ISSUE TITLE
Snapdrop does not work with Chrome and Safari (to and from)

### ISSUE THREAD

**Issue by Bellisario** [RobinLinus/snapdrop#190]
Console reports this problem...

```
Uncaught DOMException: Failed to execute 'createDataChannel' on 'RTCPeerConnection': RTCDataChannel creation failed
    at RTCPeer._openChannel (https://snapdrop.net/scripts/network.js:255:36)
    at RTCPeer._connect (https://snapdrop.net/scripts/network.js:239:18)
    at RTCPeer.refresh (https://snapdrop.net/scripts/network.js:345:14)
    at RTCPeer._send (https://snapdrop.net/scripts/network.js:332:41)
    at FileChunker._onChunk (https://snapdrop.net/scripts/network.js:128:27)
    at FileChunker._onChunkRead (https://snapdrop.net/scripts/network.js:445:14)
    at FileReader.<anonymous> (https://snapdrop.net/scripts/network.js:429:57)
```
...and this when I'm going to trensfer files and also normal text...

```
Uncaught TypeError: Cannot read property 'iceConnectionState' of null
    at RTCPeer._onIceConnectionStateChange (network.js:318)
    at RTCPeerConnection._conn.oniceconnectionstatechange (network.js:251)
```

These disable Snapdrop use and I can't transfer anything...

**P.S.: I tried to clear all Snapdrop data (with service worker), too, but the problem is not solved.**

**Comment by Alfxjx** [comment]
Same as your condition, can your devices find each other? My phone and PC can find each other but it failed when i tried to send file or messages

**Comment by Bellisario** [comment]
Yes, my devices can find each other. I've the same problem...
To solve the problem I had to close the browser on my phone and clear all site data on my computer and reload the page.
I think that the problem is in Safari.
