### ISSUE TITLE
Won't send files between windows and iOS

### ISSUE THREAD

**Issue by j3r1ch0** [RobinLinus/snapdrop#258]
Hi, I've tried everything trying to debug this app. It worked on time and has refused to work since. What I've done... I disabled all extensions. Still didn't work. I followed the instruction from another issue where it recommends deleting site data from the windows browser and iOS. It didn't work. I tried various browsers (edge, firefox, opera), doesn't work in any of them. From the logs in console it definitely seems to be an issue with your app itself as it doesn't seem to be compatible with the encryption required from iOS, at least not when sending from windows. It's sort of weird. Anyway... Here are the console logs... 

` WS: {ice: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:326 ICE Gathering checking
network.js:308 RTC: state changed: connecting
network.js:27 WS: {ice: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:255 Uncaught DOMException: Failed to execute 'createDataChannel' on 'RTCPeerConnection': RTCDataChannel creation failed
    at RTCPeer._openChannel (https://snapdrop.net/scripts/network.js:255:36)
    at RTCPeer._connect (https://snapdrop.net/scripts/network.js:239:18)
    at RTCPeer.refresh (https://snapdrop.net/scripts/network.js:348:14)
    at RTCPeer._send (https://snapdrop.net/scripts/network.js:335:41)
    at FileChunker._onChunk (https://snapdrop.net/scripts/network.js:128:27)
    at FileChunker._onChunkRead (https://snapdrop.net/scripts/network.js:448:14)
    at FileReader.<anonymous> (https://snapdrop.net/scripts/network.js:432:57)
_openChannel @ network.js:255
_connect @ network.js:239
refresh @ network.js:348
_send @ network.js:335
(anonymous) @ network.js:128
_onChunkRead @ network.js:448
(anonymous) @ network.js:432
load (async)
FileChunker @ network.js:432
_sendFile @ network.js:127
_dequeueFile @ network.js:117
sendFiles @ network.js:110
_onFilesSelected @ network.js:398
(anonymous) @ network.js:367
fire @ network.js:505
_onFilesSelected @ ui.js:146
(anonymous) @ ui.js:111
network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
_onError @ network.js:331
(anonymous) @ network.js:287
Promise.catch (async)
onServerMessage @ network.js:287
_onMessage @ network.js:376
(anonymous) @ network.js:365
fire @ network.js:505
_onMessage @ network.js:39
ws.onmessage @ network.js:19
network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
_onError @ network.js:331
(anonymous) @ network.js:287
Promise.catch (async)
onServerMessage @ network.js:287
_onMessage @ network.js:376
(anonymous) @ network.js:365
fire @ network.js:505
_onMessage @ network.js:39
ws.onmessage @ network.js:19
network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
_onError @ network.js:331
(anonymous) @ network.js:287
Promise.catch (async)
onServerMessage @ network.js:287
_onMessage @ network.js:376
(anonymous) @ network.js:365
fire @ network.js:505
_onMessage @ network.js:39
ws.onmessage @ network.js:19
network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
_onError @ network.js:331
(anonymous) @ network.js:287
Promise.catch (async)
onServerMessage @ network.js:287
_onMessage @ network.js:376
(anonymous) @ network.js:365
fire @ network.js:505
_onMessage @ network.js:39
ws.onmessage @ network.js:19
network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
_onError @ network.js:331
(anonymous) @ network.js:287
Promise.catch (async)
onServerMessage @ network.js:287
_onMessage @ network.js:376
(anonymous) @ network.js:365
fire @ network.js:505
_onMessage @ network.js:39
ws.onmessage @ network.js:19
network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
2network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
_onError @ network.js:331
(anonymous) @ network.js:287
Promise.catch (async)
onServerMessage @ network.js:287
_onMessage @ network.js:376
(anonymous) @ network.js:365
fire @ network.js:505
_onMessage @ network.js:39
ws.onmessage @ network.js:19
network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
_onError @ network.js:331
(anonymous) @ network.js:287
Promise.catch (async)
onServerMessage @ network.js:287
_onMessage @ network.js:376
(anonymous) @ network.js:365
fire @ network.js:505
_onMessage @ network.js:39
ws.onmessage @ network.js:19
network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
_onError @ network.js:331
(anonymous) @ network.js:287
Promise.catch (async)
onServerMessage @ network.js:287
_onMessage @ network.js:376
(anonymous) @ network.js:365
fire @ network.js:505
_onMessage @ network.js:39
ws.onmessage @ network.js:19
network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"}
network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
_onError @ network.js:331
(anonymous) @ network.js:287
Promise.catch (async)
onServerMessage @ network.js:287
_onMessage @ network.js:376
(anonymous) @ network.js:365
fire @ network.js:505
_onMessage @ network.js:39
ws.onmessage @ network.js:19
network.js:326 ICE Gathering disconnected
network.js:308 RTC: state changed: failed
network.js:302 RTC: channel closed f1c01734-cd4a-459e-90f0-04c6979248be
network.js:27 WS: {type: "ping"} `

**Comment by vipvic** [comment]
the web didn't work too (u‿ฺu✿ฺ)



Send from Samsung Galaxy S8



-------- 原始信息 --------
发件人： Mike <notifications@github.com>
日期: 2021/2/17 04:03 (GMT+08:00)
收件人： RobinLinus/snapdrop <snapdrop@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： [RobinLinus/snapdrop] Won't send files between windows and iOS (#258)


Hi, I've tried everything trying to debug this app. It worked on time and has refused to work since. What I've done... I disabled all extensions. Still didn't work. I followed the instruction from another issue where it recommends deleting site data from the windows browser and iOS. It didn't work. I tried various browsers (edge, firefox, opera), doesn't work in any of them. From the logs in console it definitely seems to be an issue with your app itself as it doesn't seem to be compatible with the encryption required from iOS, at least not when sending from windows. It's sort of weird. Anyway... Here are the console logs...

WS: {ice: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:326 ICE Gathering checking network.js:308 RTC: state changed: connecting network.js:27 WS: {ice: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:255 Uncaught DOMException: Failed to execute 'createDataChannel' on 'RTCPeerConnection': RTCDataChannel creation failed at RTCPeer._openChannel (https://snapdrop.net/scripts/network.js:255:36) at RTCPeer._connect (https://snapdrop.net/scripts/network.js:239:18) at RTCPeer.refresh (https://snapdrop.net/scripts/network.js:348:14) at RTCPeer._send (https://snapdrop.net/scripts/network.js:335:41) at FileChunker._onChunk (https://snapdrop.net/scripts/network.js:128:27) at FileChunker._onChunkRead (https://snapdrop.net/scripts/network.js:448:14) at FileReader.<anonymous> (https://snapdrop.net/scripts/network.js:432:57) _openChannel @ network.js:255 _connect @ network.js:239 refresh @ network.js:348 _send @ network.js:335 (anonymous) @ network.js:128 _onChunkRead @ network.js:448 (anonymous) @ network.js:432 load (async) FileChunker @ network.js:432 _sendFile @ network.js:127 _dequeueFile @ network.js:117 sendFiles @ network.js:110 _onFilesSelected @ network.js:398 (anonymous) @ network.js:367 fire @ network.js:505 _onFilesSelected @ ui.js:146 (anonymous) @ ui.js:111 network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable _onError @ network.js:331 (anonymous) @ network.js:287 Promise.catch (async) onServerMessage @ network.js:287 _onMessage @ network.js:376 (anonymous) @ network.js:365 fire @ network.js:505 _onMessage @ network.js:39 ws.onmessage @ network.js:19 network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable _onError @ network.js:331 (anonymous) @ network.js:287 Promise.catch (async) onServerMessage @ network.js:287 _onMessage @ network.js:376 (anonymous) @ network.js:365 fire @ network.js:505 _onMessage @ network.js:39 ws.onmessage @ network.js:19 network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable _onError @ network.js:331 (anonymous) @ network.js:287 Promise.catch (async) onServerMessage @ network.js:287 _onMessage @ network.js:376 (anonymous) @ network.js:365 fire @ network.js:505 _onMessage @ network.js:39 ws.onmessage @ network.js:19 network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable _onError @ network.js:331 (anonymous) @ network.js:287 Promise.catch (async) onServerMessage @ network.js:287 _onMessage @ network.js:376 (anonymous) @ network.js:365 fire @ network.js:505 _onMessage @ network.js:39 ws.onmessage @ network.js:19 network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable _onError @ network.js:331 (anonymous) @ network.js:287 Promise.catch (async) onServerMessage @ network.js:287 _onMessage @ network.js:376 (anonymous) @ network.js:365 fire @ network.js:505 _onMessage @ network.js:39 ws.onmessage @ network.js:19 network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} 2network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable _onError @ network.js:331 (anonymous) @ network.js:287 Promise.catch (async) onServerMessage @ network.js:287 _onMessage @ network.js:376 (anonymous) @ network.js:365 fire @ network.js:505 _onMessage @ network.js:39 ws.onmessage @ network.js:19 network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable _onError @ network.js:331 (anonymous) @ network.js:287 Promise.catch (async) onServerMessage @ network.js:287 _onMessage @ network.js:376 (anonymous) @ network.js:365 fire @ network.js:505 _onMessage @ network.js:39 ws.onmessage @ network.js:19 network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable _onError @ network.js:331 (anonymous) @ network.js:287 Promise.catch (async) onServerMessage @ network.js:287 _onMessage @ network.js:376 (anonymous) @ network.js:365 fire @ network.js:505 _onMessage @ network.js:39 ws.onmessage @ network.js:19 network.js:27 WS: {sdp: {…}, type: "signal", sender: "f1c01734-cd4a-459e-90f0-04c6979248be"} network.js:331 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable _onError @ network.js:331 (anonymous) @ network.js:287 Promise.catch (async) onServerMessage @ network.js:287 _onMessage @ network.js:376 (anonymous) @ network.js:365 fire @ network.js:505 _onMessage @ network.js:39 ws.onmessage @ network.js:19 network.js:326 ICE Gathering disconnected network.js:308 RTC: state changed: failed network.js:302 RTC: channel closed f1c01734-cd4a-459e-90f0-04c6979248be network.js:27 WS: {type: "ping"}

**Comment by GN6621** [comment]
Same here. I finally got it to work by restarting the laptop and the iPhone.  Until next time .... Which is a shame, because this is a great app!!!! I hope you can fix this :-)

**Comment by j3r1ch0** [comment]
> Same here. I finally got it to work by restarting the laptop and the iPhone. Until next time .... Which is a shame, because this is a great app!!!! I hope you can fix this :-)

It’s really weird because now it works just fine for me with my exact same configuration on my devices and network. I don’t see a patch in the project for it so idk. It works flawlessly now every single time though. I don’t get it.

**Comment by ueen** [comment]
Also Mac<->Windows7 with Firefox an both doesnt work :(
